version: '3'
services:
  contentmanagerweb:
    image: joaopio/content-manager-web
    depends_on:
      - contentmanagerbff
      - contentapi
      - mysql
    environment:
      - BFF_BASE_ADDRESS=https://socialmovie.minivps.info:5000
      - AUTHORIZATOR_BASE_ADDRESS=https://socialmovie.minivps.info:3000
      - CONTENT_SERVER_BASE_ADDRESS=https://socialmovie.minivps.info:4000
    volumes:
      - /keys:/etc/nginx/keys
    networks:
      - contentmanagernetwork
    ports:
      - "443:443"

  contentmanagerbff:
    image: joaopio/content-manager-bff
    depends_on:
      - contentapi
      - mysql
    environment:
      - CONTENT_API_URL=http://contentapi
    networks:
      - contentmanagernetwork
    ports:
      - "5000:5000"

  contentapi:
    image: joaopio/content-api
    depends_on:
      - mysql
    environment:
      - CONNECTION_STRING=Server=mysql;Database=content;Uid=content;Pwd=content1234
      - SSH_HOST=contentserver
      - SSH_USERNAME=content
      - SSH_PASSWORD=password
      - SSH_PORT=22
      - MEDIAFILES_BASE_PATH=/content
    networks:
      - contentmanagernetwork
    ports:
      - "8080:80"

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=content
      - MYSQL_USER=content
      - MYSQL_PASSWORD=content1234
    networks:
      - contentmanagernetwork
    ports:
      - "3306:3306"

  contentserver:
    image: joaopio/content-server
    ports:
      - "2222:22"
      - "4000:80"
    environment:
      - NGINX_PORT=80
      - CONTENT_PATH=/content
      - CONTENT_AUTH_URL=http://contentauthorizator
      - USER_NAME=content
      - USER_PASSWORD=password
    volumes:
      - /content:/content
    networks:
      - contentmanagernetwork

  contentauthorizator:
    image: joaopio/content-authorizator
    environment:
      - API_PORT=80
    ports:
      - "3000:80"
    networks:
      - contentmanagernetwork

networks:
  contentmanagernetwork:
